---
name: Update t2bce

on:
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout Repo'
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Get the latest version
        id: publish
        run: |
          git clone https://github.com/kaiT2en/KaiT2en-Fedora
          for i in t2bce_audio-alsa-ucm-conf t2bce_audio t2bce_ave t2bce_core t2bce_dma t2bce_vhci
          do
          rm -rf "$i"
          cp -r ./KaiT2en-Fedora/modules/"$i" ./
          done
          rm -rf KaiT2en-Fedora
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update t2bce"

      - name: Push changes to the repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
